---
- name: Install Required Packages
  apt: pkg={{ package }} state=present
  
  vars:
    package:
      - nginx

- name: Deploy nginx Default Configuration
  template:
    src: ./etc/nginx/sites-available/default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'

- name: Create alias Folder
  file:
    path: "{{ item.alias }}"
    owner: www-data
    group: www-data
    mode: '0755'
    state: directory
  with_items: "{{ nginx }}"

- name: Create index.html File
  template:
    src: ./var/www/index.html.j2
    dest: "{{ item.alias }}/index.html"
    owner: www-data
    group: www-data
    mode: '0644'
  with_items: "{{ nginx }}"

- name: Reload nginx Service (Example Module systemd)
  systemd:
    name: nginx.service
    state: reloaded

- name: Reload nginx Service (Example Module raw)
  raw: systemctl reload nginx.service
